---
title: "BC LTC Analysis"
author: "KT Hobbs"
date: "02/08/2020"
output: html_document
---

## Import and prepare the data
```{r results="hide"}
library(skimr)

# Import the data
df <- read.csv("data/bc_ltc.csv", na.strings="", header=TRUE)
skim(df)
```


```{r}
# drop unneccessary columns
df2 <- df[,-c(1,3:12, 14:15)]
colnames(df2)

# Check for R skewness in numeric predictors
library(e1071)

listofcols = c("accreditation", "Private.beds..not.publicly.funded.", "Total.beds", "Total.direct.care.hours..hours.per.resident.per.day.", "Number.substantiated.licensing.complaints",
               "Number.of.licensing.infractions.found", "Average.age.of.population", "Average.age.of.population",
               "residents_council", 'Hygiene...communicable.disease.control', "family_council")


numerical <- c('Number.of.dead', 'Number.of.beds..appx.', 'Private.beds..not.publicly.funded.', 
               'Publicly.funded.beds..short..and.long.term.', 'Total.beds', 'Private.rooms', 
               'Semi.private.rooms', 'Multi.person.rooms')

for (each in numerical){
  print(each)
  print(class(data[,each]))
  # print(skewness(data$each))
  # qqnorm(data$each, main = each)
  # qqline(data$each, col = 'red')
}


```

