---
title: "bc_mainland_analysis"
author: "Ngan Lyle"
date: "28/08/2020"
output: html_document
---
## Import and prepare the data
```{r results="hide"}
library(skimr)
# library(dplyr)

# Import the data
df <- read.csv("../data/BC/ngan_bc_ltc_mainland.csv", na.strings="", header=TRUE)
str(df)
skim(df)
# dput(names(df))
```


```{r, echo=FALSE}
# Change datatypes as needed
listofcol = list('FACILITY_NAME', 'HCC_CODE', 'STREET_ADDRESS', 'CITY', 'POSTAL')
for (each in listofcol){
  df[, each] <- as.character(df[, each])
}

listofcol = list("outbreak", "rooms_semi_binary", "rooms_multi_binary", "rooms_shared", 
"resident_council", "family_council", "res_fam_council", "beds_privatebinary")
for (each in listofcol){
  df[, each] <- as.factor(df[, each])
}

str(df)
dput(names(df))

# 34/131 homes had an outbreak
# table(df['outbreak'])
```

```{r, include=FALSE}
# Divide the variables into numeric and categorical types

num <- c("BEDS_TOTAL", 
"INCIDENT_OUTBREAK_100", "AGE", "FEMALE", "AGE_85_PLUS", "AGE_UNDER_65", 
"DEPRESSION", "ADL_DEPENDENT", "CPS_SEVERE", "DEMENTIA", 
"ABS_PHYS_ABUSIVE", "ISE", "ISE_LOW", "CMI", "THERAPY_PT", "THERAPY_RT", 
"THERAPY_OT", "MEDS_DEPRESSION", "MEDS_ANTIPSYCHOTICS", "RESTRAINTS", 
"INSPECTIONS", "complaints_100", "sub_complaints_100", 
"incident_100sumXoutbreak", "infractions_disease_100", "infractions_100Xdisease"
)

cat <- c("HLTH_AUTH", "OWNERSHIP", "REGULATION", "ACCRED_STATUS", 
         "rooms_semi_binary", "rooms_multi_binary", 
"rooms_shared", "resident_council", "family_council", "res_fam_council", 
"beds_privatebinary"
)

# Subset the data for analysis
data <- subset(df, select = c('outbreak', num, cat))

str(data)
dput(names(data))

```

## LASSO
```{r }
# https://stats.stackexchange.com/questions/72251/an-example-lasso-regression-using-glmnet-for-binary-outcome
library(glmnet)

# model.matrix() automatically transforms any qualitative variables into dummy variables
# Trim the first column leaving only predictors
x = model.matrix(outbreak~. , data = data)[,-1]
# y <- as.matrix(subset(data, select = c('outbreak')))
y <- data.matrix(data[,1])

# Note alpha=1 for lasso only and can blend with ridge penalty down to
# alpha=0 ridge only
glmmod <- glmnet(x, y, alpha = 1, family = 'binomial')

# Plot variable coefficients vs. shrinkage parameter lambda
plot(glmmod, xvar = 'lambda', label = TRUE)

cv.glmmod <- cv.glmnet(x, y, alpha=1, family = 'binomial')
plot(cv.glmmod)
coef(cv.glmmod)
cv.glmmod$lambda.min
coef(cv.glmmod, s = "lambda.min")

```

## Group LASSO
```{r, }
library(grplasso)
x <- model.matrix(outbreak~. , data = data)[,-1]
y <- as.numeric(data.matrix(data[,1]))

# Index the predictors so that they are grouped
index = c(1, 2, 3, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 7, 7, 7, 8, 9, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26)

## Use a multiplicative grid for the penalty parameter lambda, starting
## at the maximal lambda value
lambda <- lambdamax(x, y = y, index = index, penscale = sqrt,
                    model = LogReg()) * 0.5^(0:5)

## Fit the solution path on the lambda grid
grplass_mod <- grplasso(x, y, index = index, lambda = lambda, model = LogReg(),
                penscale = sqrt,
                control = grpl.control(update.hess = "lambda", trace = 0),
                center = FALSE)

coef(grplass_mod)
plot(grplass_mod)

```
  

## Using the stepAIC() function
```{r }
library(MASS)

null <- glm(outbreak ~ 1, family = "binomial", data=data) # 1 here means the intercept 
full <- glm(outbreak ~ 
    BEDS_TOTAL + 
    INCIDENT_OUTBREAK_100 +
    AGE + FEMALE + AGE_85_PLUS + AGE_UNDER_65 +
    DEPRESSION + ADL_DEPENDENT + CPS_SEVERE + DEMENTIA + ABS_PHYS_ABUSIVE +
    # ISE + 
    ISE_LOW + 
    # CMI + 
    THERAPY_PT + THERAPY_RT + THERAPY_OT +
    MEDS_DEPRESSION + MEDS_ANTIPSYCHOTICS + RESTRAINTS +
    INSPECTIONS + 
    beds_privateprop +
    complaints_100 + sub_complaints_100 +
    # incident_100sum +
    incident_100sumXoutbreak +
    # infractions_100 +
    infractions_disease_100 +
    infractions_100Xdisease +
    HLTH_AUTH + 
    OWNERSHIP +
    REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + rooms_shared +
    resident_council + family_council + res_fam_council + 
    beds_privatebinary 
    # ownership_HA
  ,
  family = "binomial", data=data)

stepAIC(full, scope=list(lower=null, upper=full), data=data, direction='backward')
# stepAIC(null, scope=list(lower=null, upper=full), data=data, direction='forward')
```

## Fit logistic regression
```{r }
# Fit logistic regression using transformed data
fit = glm(outbreak~., family=binomial, data=data)
summary(fit)
```

```{r }
# Backward selection using AIC
fit_back_aic = step(fit, direction = "backward")
coef(fit_back_aic)

# Bacward selection using BIC
n = length((resid(fit)))
fit_back_bic = step(fit, direction = "backward", k = log(n))

coef(fit_back_bic)

# A function which calculates the LOOCV RMSE
calc_loocv_rmse = function(model) {
  sqrt(mean((resid(model) / (1 - hatvalues(model))) ^ 2))
}

# Calculate LOOCV RMSE for each model
calc_loocv_rmse(fit)
calc_loocv_rmse(fit_back_aic)
calc_loocv_rmse(fit_back_bic)
```

# Transformation
```{r, }
## Assessing skewness
# Check for R skewness in numeric predictors
library(e1071)

for (each in num){
  print(each)
  print(skewness(data[[each]]))
  # qqnorm(data[[each]], main = each)
  # qqline(data[[each]], col = 'red')
}

# Assess numeric predictors for 0s
for (each in num){
  print(each)
  print(summary(df[[each]]))
}

# List of numeric variables without 0s
list_non0s <- c(
  "BEDS_TOTAL", 
  "AGE", 
  "FEMALE", 
  "ISE_LOW", 
  "CMI", 
  "DCH_NURSE",
  "DCH_ALLLIED",
  "DCH_TOTAL"
)

# List of numeric variables with 0s
list_0s <- setdiff(num, list_non0s)

# List of numeric variables without 0s that are right skewed
list_non0s_right <- c(
  "BEDS_TOTAL", 
  "CMI", 
  "DCH_NURSE",
  "DCH_ALLLIED",
  "DCH_TOTAL"
)

# List of numeric variables without 0s that are left skewed
list_non0s_left <- c(
  "AGE", 
  "FEMALE", 
  "ISE_LOW"
)

library(rcompanion)

# Visualize the effect of square root and log transformations on right skewed data without 0s
for (each in list_non0s_right) {  
  plotNormalHistogram(x = data[[each]], main = each)
  plotNormalHistogram(x = sqrt(data[[each]]), main = c(each, 'sqrt trans'))
  plotNormalHistogram(x = log(data[[each]]), main = c(each, 'log trans'))
}

# Can log transform all except BEDS_TOTAL

# Visualize the effect of square root and cube root transformation on right skewed data with 0s
for (each in list_0s) {  
  plotNormalHistogram(x = data[[each]], main = each)
  plotNormalHistogram(x = sqrt(data[[each]]), main = c(each, 'sqrt trans'))
  plotNormalHistogram(x = (data[[each]])^1/3, main = c(each, 'cube rt'))
}

# Generally the cube root transformation does not add much to a square root transformation

## Transform the data
# # Square root transform in place
# data[c(list_0s)] <- sqrt(data[c(list_0s)])
# 
# skim(data)


```

```{r, }

```

```{r, }

```

```{r }

```

```{r, }

```

```{r }

```

