---
title: "bc_ltc_analysis"
author: "Ngan Lyle"
date: "21/08/2020"
output: html_document
---

## Import and prepare the data
```{r results="hide"}
library(skimr)
library(dplyr)

# Import the data
df <- read.csv("../data/BC/bc_ltc_selected_sep18.csv", na.strings="", header=TRUE)
str(df)
```

```{r, echo=FALSE}
# Change datatypes as needed
listofcol = list('FACILITY_NAME', 'HCC_CODE', 'STREET_ADDRESS', 'CITY', 'POSTAL')

for (each in listofcol){
  df[, each] <- as.character(df[, each])
}

listofcol = list('outbreak',
  # 'ownership_HA',
  'rooms_semi_binary', 'rooms_multi_binary', 'rooms_shared', 'resident_council', 'family_council',
  'res_fam_council', 'beds_privatebinary')

for (each in listofcol){
  df[, each] <- as.factor(df[, each])
}

str(df)
# dput(names(df))
```

```{r, include=FALSE}
# Generate the data for analysis
# Create lists of variables used to filter data for analysis

# Selected data
num <- c("BEDS_TOTAL", "INSPECTIONS", 
  # "beds_privateprop",
  "infractions_100Xdisease", "infractions_disease_100")
cat <- c(
  "HLTH_AUTH", 
  # 'ownership_HA',
  "OWNERSHIP",
  "REGULATION", "ACCRED_STATUS", 
  "rooms_semi_binary", "rooms_multi_binary", "rooms_shared",
  "resident_council", "family_council",
  "res_fam_council",
  "beds_privatebinary"
  )

# Data with outbreak as outcome
data <- subset(df, select = c('outbreak', num, cat))

# Data with cases/deaths as outcome
# As cases/deaths can only occur in homes with an outbreak will subset to include only homes with an outbreak
df_outbreak <- subset(df, outbreak == 1)
data_cases <- subset(df_outbreak, select = c('Total.Confirmed.Cases', num, cat))
data_deaths <- subset(df_outbreak, select = c('Total.Deaths', num, cat))

# str(data)
```

## LASSO
```{r }
# https://stats.stackexchange.com/questions/72251/an-example-lasso-regression-using-glmnet-for-binary-outcome
library(glmnet)

# model.matrix() automatically transforms any qualitative variables into dummy variables
# Trim the first column leaving only predictors
x = model.matrix(outbreak~. , data = data)[,-1]
# y <- as.matrix(subset(data, select = c('outbreak')))
y <- data.matrix(data[,1])

# Note alpha=1 for lasso only and can blend with ridge penalty down to
# alpha=0 ridge only
glmmod <- glmnet(x, y, alpha = 1, family = 'binomial')

# Plot variable coefficients vs. shrinkage parameter lambda
plot(glmmod, xvar = 'lambda', label = TRUE)

cv.glmmod <- cv.glmnet(x, y, alpha=1, family = 'binomial')


plot(cv.glmmod)
cv.glmmod$lambda.min

coef(cv.glmmod, s = "lambda.min")

```

## Using the stepAIC() function
```{r }
library(MASS)

null <- glm(outbreak ~ 1, family = "binomial", data=data) # 1 here means the intercept 
full <- glm(
  outbreak ~ BEDS_TOTAL + INSPECTIONS + 
    # beds_privateprop + 
    infractions_100Xdisease + infractions_disease_100 + 
    HLTH_AUTH + 
    OWNERSHIP +
    # ownership_HA +
    REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + rooms_shared +
    resident_council + family_council +
    res_fam_council +
    beds_privatebinary
  , family = "binomial", data=data)

stepAIC(full, scope=list(lower=null, upper=full), data=data, direction='backward')
# stepAIC(null, scope=list(lower=null, upper=full), data=data, direction='forward')
```

# Poisson regression
```{r }
# fit_poi <- glm(Total.Confirmed.Cases/BEDS_TOTAL~ ., family = poisson, data = data_cases, weight = BEDS_TOTAL)
# summary(fit_poi)

fit_poi <- glm(Total.Confirmed.Cases~ 
    INSPECTIONS + 
    # beds_privateprop +
    infractions_100Xdisease + infractions_disease_100 + 
    HLTH_AUTH + 
    OWNERSHIP +
    # ownership_HA +
    REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + 
    # rooms_shared +
    resident_council + family_council +
    # res_fam_council +
    beds_privatebinary, 
    family = poisson, data = data_cases, offset = log(BEDS_TOTAL))
summary(fit_poi)

fit_poi <- glm(Total.Deaths~ 
    INSPECTIONS + 
    # beds_privateprop +
    infractions_100Xdisease + infractions_disease_100 + 
    HLTH_AUTH + 
    OWNERSHIP +
    # ownership_HA +
    REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + 
    # rooms_shared +
    resident_council + family_council +
    # res_fam_council +
    beds_privatebinary,
  family = poisson, data = data_deaths, offset = log(BEDS_TOTAL))
summary(fit_poi)
```

```{r }

```


## Fit logistic regression
```{r }
# Fit logistic regression using transformed data
fit = glm(outbreak~., family=binomial, data=data)
summary(fit)
```

### Backwards Selection
```{r, include=FALSE}
# Manual
fit <- update(fit, .~. -rooms_semi_binary)
summary(fit)
fit <- update(fit, .~. -res_fam_council)
summary(fit)
fit <- update(fit, .~. -rooms_multi_binary)
summary(fit)
fit <- update(fit, .~. -ACCRED_STATUS)
summary(fit)
fit <- update(fit, .~. -OWNERSHIP)
summary(fit)
fit <- update(fit, .~. -beds_privateprop)
summary(fit)
fit <- update(fit, .~. -REGULATION)
summary(fit)
fit <- update(fit, .~. -INSPECTIONS)
summary(fit)
fit <- update(fit, .~. -infractions_100)
summary(fit)
fit <- update(fit, .~. -resident_council)
summary(fit)
fit <- update(fit, .~. -infractions_disease_100)
summary(fit)
fit <- update(fit, .~. -beds_privatebinary)
summary(fit)
fit <- update(fit, .~. -family_council)
summary(fit)
fit <- update(fit, .~. -HLTH_AUTH)
summary(fit)

```


```{r }
# Backward selection using AIC
fit_back_aic = step(fit, direction = "backward")
coef(fit_back_aic)

# Backward selection using BIC
n = length((resid(fit)))
fit_back_bic = step(fit, direction = "backward", k = log(n))
coef(fit_back_bic)

# A function which calculates the LOOCV RMSE
calc_loocv_rmse = function(model) {
  sqrt(mean((resid(model) / (1 - hatvalues(model))) ^ 2))
}

# Calculate LOOCV RMSE for each model
calc_loocv_rmse(fit)
calc_loocv_rmse(fit_back_aic)
calc_loocv_rmse(fit_back_bic)

# Forward selection
null <- glm(outbreak ~ 1, family = "binomial", data=data) # 1 here means the intercept 
full <- glm(
  outbreak ~ BEDS_TOTAL + INSPECTIONS + 
    # beds_privateprop + 
    infractions_100 + infractions_disease_100 + 
    HLTH_AUTH + OWNERSHIP + REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + rooms_shared + 
    resident_council + family_council + 
    # res_fam_council + 
    beds_privatebinary, family = "binomial", data=data)

fit_start = glm(outbreak ~ 1, family=binomial, data = data)
fit_fwd_aic = step(
  fit_start, 
  scope = outbreak ~ BEDS_TOTAL + INSPECTIONS + 
    # beds_privateprop + 
    infractions_100 + infractions_disease_100 + 
    HLTH_AUTH + OWNERSHIP + REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + rooms_shared + 
    resident_council + family_council + 
    # res_fam_council + 
    beds_privatebinary, 
  direction = "forward")
```

## Stepwise Selection
```{r }
fit_both_aic = step(
  fit_start, 
  scope = outbreak ~ BEDS_TOTAL + INSPECTIONS + 
    # beds_privateprop + 
    infractions_100 + infractions_disease_100 + 
    HLTH_AUTH + OWNERSHIP + REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + rooms_shared + 
    resident_council + family_council + 
    # res_fam_council + 
    beds_privatebinary, 
  direction = "both")

fit_both_bic = step(
  fit_start, 
  scope = outbreak ~ BEDS_TOTAL + INSPECTIONS + 
    # beds_privateprop + 
    infractions_100 + infractions_disease_100 + 
    HLTH_AUTH + OWNERSHIP + REGULATION + ACCRED_STATUS + 
    rooms_semi_binary + rooms_multi_binary + rooms_shared + 
    resident_council + family_council + 
    # res_fam_council + 
    beds_privatebinary, 
  direction = "both", k = log(n))
```

### All Possible Models
```{r }
library(leaps)
all_fit = summary(regsubsets(outbreak ~ ., data = data))

# Determine the best model for a given size based on RSS
all_fit$which
all_fit$rss
all_fit$adjr2

# Model with highest adjusted R2
best_r2_ind = which.max(all_fit$adjr2)
all_fit$which[best_r2_ind,] # extract predictors

# Calculate the AIC and BIC for each of the models with the best RSS
p = length(coef(fit))
n = length(resid(fit))
fit_aic = n * log(all_fit$rss / n) + 2 * (2:p)

best_aic_ind = which.min(fit_aic)
all_fit$which[best_aic_ind,]

fit_best_aic = glm(outbreak ~ BEDS_TOTAL + HLTH_AUTH + rooms_shared, family = 'binomial', data = data)
summary(fit_best_aic)

```


```{r }
# Compare AIC for our fitted models
extractAIC(fit_best_aic)
extractAIC(fit_back_aic)
extractAIC(fit_fwd_aic)

plot(fit_aic ~ I(2:p), ylab = "AIC", xlab = "p, number of parameters", 
     pch = 20, col = "dodgerblue", type = "b", cex = 2,
     main = "AIC vs Model Complexity")
```


```{r }
# Most homes have a family_council
# 8/46 homes without a family council had an outbreak
# 26/251 with a family council had an outbreak
xtabs(~OWNERSHIP + rooms_shared, data=df)
xtabs(~OWNERSHIP + rooms_multi_binary, data=df)

Review the minority of homes without a family council
subset(df, FAMILY_COUNCIL == 'False')
```

## Transforming covariates
```{r, include=FALSE}
## Assessing skewness
# Check for R skewness in numeric predictors
library(e1071)

listofcol = c(num)

for (each in listofcol){
  print(each)
  print(skewness(data[[each]]))
  qqnorm(data[[each]], main = each)
  qqline(data[[each]], col = 'red')
}

# Assess variables for 0s
for (each in listofcol){
  print(each)
  print(summary(df[[each]]))
}

library(rcompanion)

## Explore the variables for transformation
# Visualize the effect of square root transformations on the  predictors
for (each in listofcol) {  
  plotNormalHistogram(x = data[[each]], main = each)
  plotNormalHistogram(x = sqrt(data[[each]]), main = c(each, 'sqrt trans'))
}

## Transform the data
# Square root transform in place
data[listofcol] <- sqrt(data[listofcol])

skim(data)
```


```{r }

```

```{r }

```
