---
title: "ltc_analysis_ON_deaths"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
# set.seed(100)
```

# Import and prepare the data
```{r }
library(devtools)
library(broom)

# Import the data
df <- read.csv("../data_output/merged_LTC_odhf_quality.csv", na.strings="", header=TRUE)
# head(df)

# Change variable data types
# To factor
df[, 'outbreak'] <- as.factor(df[, 'outbreak'])

# To datetime
cols <- c( "first_inspection_date", 
           "last_inspection_date", 
           "last_rqi_date",
           "date_first_outbreak", 
           "date_max_cases", 
           "date_max_HCWcases", 
           "date_first_resolved")
df[cols] <- lapply(df[cols], as.Date)

# To char
cols <- c("cleaned_name", 
          "name", 
          "address", 
          "city", 
          "postal_code", 
          "CSDname")
df[cols] <- lapply(df[cols], as.character)

```

## Subset the data
```{r, }
# Generate the data for analysis
# Create lists of variables used to filter data for analysis

outcomes = c(
  "outbreak", 
  "cum_resident_deaths", 
  "max_resident_cases", 
  "max_hcw_cases"
  )

profile = c(
  "home_type", 
  "number_beds",
  "short_stay",
  "residents_council",
  "family_council",
  "accreditation"
  )

location = c(
  'address', 
  'LHIN', 
  'city', 
  'postal_code', 
  'CSDname', 
  'CSDuid', 
  'latitude', 
  'longitude')

inspections_1y = c(
  'X1y_inspections',
  'X1y_withOrders'
)

inspections_2y = c(
    'X2y_inspections'
  , "X2y_withOrders"
  )

inspections_3y = c(
    'X3y_inspections'
  , "X3y_withOrders"
  )


inspections = c(inspections_2y, inspections_3y, inspections_1y)

```

## Subset data for analysis
```{r }
# Subset southern ON homes, 554 homes
df_southON <- df[substr(trimws(df$postal_code),1,1)!='P',]

# As cases/deaths can only occur in homes with an outbreak will subset to include only homes with an outbreak
df_southON_outbreak <- subset(df_southON, outbreak == 1)

data <- subset(df_southON_outbreak, select = c('cum_resident_deaths', profile, inspections_2y))

# skim(data)
# View(colnames(data))
# dput(names(df))

```


```{r, include=FALSE, eval=FALSE}
# Look at the distribution of count data
hist(data$cum_resident_deaths)
mean(data$cum_resident_deaths)
var(data$cum_resident_deaths)

```

# LASSO
## LASSO - CovTest
```{r }
# install.packages('covTest_1.02.tar.gz', repos = NULL, type="source")
library(covTest)
x <- model.matrix(cum_resident_deaths~., data = data)[,-1]
y <- data.matrix(data[,1])
a = lars(x,y)

# a$beta
a$act
a$pathobj
# a$a0

# plot(a)
# summary(a)

covTest(a,x,y)





```

## LASSO - CV
```{r }
grid = exp(seq(-5, 5, length=100))
cv.glmmod <- cv.glmnet(x, y, alpha=1, lambda = grid)
# cv.glmmod <- cv.glmnet(x, y, alpha=1)
plot(cv.glmmod)
coef(cv.glmmod)
coef(cv.glmmod, s = "lambda.min")

```
# Regression models
## Use selected covariates based on a covTest p-value <0.5
## Quasi-poisson regression with offset for the number of beds 
```{r }
# fit_poi <- glm(Total.Confirmed.Cases/BEDS_TOTAL~ ., family = poisson, data = data_cases, weight = BEDS_TOTAL)
# summary(fit_poi)

fit_poi <- glm(cum_resident_deaths~ 
  home_type
  # + X1y_withOrders
  # + X1y_inspections
  + X2y_inspections
  + X2y_withOrders
  # + X3y_inspections
  # + X3y_withOrders
  # + log(number_beds)
  , family = quasipoisson
  , data = data
  , offset = log(number_beds)
  )
summary(fit_poi)

```
## Zero-inflated negative binomial regression with offset for number of beds
```{r }
library(pscl)
mod = zeroinfl(cum_resident_deaths~
                 home_type
               + log(number_beds)
  # + X1y_withOrders
  # + X1y_inspections
  + X2y_inspections
  # + X3y_inspections
               | home_type
               + log(number_beds)
  # + X1y_withOrders
  # + X1y_inspections
  + X2y_inspections
  # + X3y_inspections
               , data = data
               , dist = 'negbin'
               , offset = log(number_beds)
               )
summary(mod)
confint(mod)
```


<!-- ## Use the entire southON dataset (not subset with outbreak) -->
<!-- ```{r } -->
<!-- data <- subset(df_southON, select = c('cum_resident_deaths', profile, inspections_2y, inspections_5y)) -->
<!-- data$cum_resident_deaths[is.na(data$cum_resident_deaths)] = 0 -->

<!-- ``` -->

<!-- ## LASSO - CovTest -->
<!-- ```{r } -->
<!-- x <- model.matrix(cum_resident_deaths~., data = data)[,-1] -->
<!-- y <- data.matrix(data[,1]) -->
<!-- a = lars(x,y) -->

<!-- # a$beta -->
<!-- a$act -->
<!-- # a$pathobj -->
<!-- # a$a0 -->

<!-- # plot(a) -->
<!-- # summary(a) -->

<!-- ``` -->

<!-- ```{r } -->
<!-- covTest(a,x,y) -->
<!-- # Both number_beds and home_type have significant p-values -->
<!-- ``` -->

<!-- ## LASSO - CV -->
<!-- ```{r } -->
<!-- grid = exp(seq(-5, 5, length=100)) -->
<!-- cv.glmmod <- cv.glmnet(x, y, alpha=1, lambda = grid) -->
<!-- # cv.glmmod <- cv.glmnet(x, y, alpha=1) -->
<!-- plot(cv.glmmod) -->
<!-- coef(cv.glmmod) -->
<!-- coef(cv.glmmod, s = "lambda.min") -->

<!-- ``` -->

<!-- Zero-inflated negative binomial regression with offset for number of beds -->
<!-- ```{r } -->
<!-- library(pscl) -->
<!-- mod = zeroinfl(cum_resident_deaths~  -->
<!--                  home_type  -->
<!--                + log(number_beds) -->
<!--                + X5y_withOrders_per_year -->
<!--                | home_type  -->
<!--                + log(number_beds) -->
<!--                + X5y_withOrders_per_year -->
<!--                , data = data  -->
<!--                , dist = 'negbin' -->
<!--                , offset = log(number_beds) -->
<!--                ) -->
<!-- summary(mod) -->
<!-- confint(mod) -->

<!-- ``` -->
<!-- Since we have data on whether or not homes had an outbreak, does it make sense to apply a zero inflated model? -->


<!-- ```{r, , eval=FALSE, include=FALSE} -->
<!-- # Old code -->
<!-- ## LASSO for variable selection - manual -->

<!-- library(glmnet) -->
<!-- options(max.print= 9999, width = 9999) -->
<!-- # model.matrix() automatically transforms any qualitative variables into dummy variables -->
<!-- # Trim the first column leaving only predictors -->
<!-- x <- model.matrix(cum_resident_deaths~., data = data)[,-1] -->
<!-- y <- data.matrix(data[,1]) -->

<!-- # Note alpha=1 for lasso only and can blend with ridge penalty down to -->
<!-- # alpha=0 ridge only -->
<!-- glmmod <- glmnet(x, y, alpha = 1) -->
<!-- coef(glmmod) -->

<!-- # Plot variable coefficients vs. shrinkage parameter lambda -->
<!-- plot(glmmod, xvar = 'lambda', label = TRUE) -->
<!-- plot(glmmod, xvar = 'dev', label = TRUE) -->

<!-- # As lambda decreases, the order that predictors are added to the model: -->
<!-- #      -->
<!-- #     1. home_typeMunicipal -->
<!-- #     2. short_stayYes -->
<!-- #     3. accreditationYes -->
<!-- #     4. residents_councilYes -->
<!-- #     5. family_councilYes -->
<!-- ``` -->


```{r }

```


```{r }

```


```{r }

```

