---
title: "ltc_analysis_ON"
author: "Ngan Lyle"
date: "08/09/2020"
output: html_document
---
## Import and prepare the data
```{r results="hide"}
library(skimr)

# Import the data
df <- read.csv("../data_output/merged_LTC_odhf_quality.csv", na.strings="", header=TRUE)
skim(df)
head(df)
str(df)

# Convert date column into date format
df$first_inspection_date <- as.Date(df$first_inspection_date)
df$first_inspection_year <- format(df$first_inspection_date,"%Y")
df$first_inspection_year <- as.numeric(df$first_inspection_year)

# Earliest date of first inspection was in 2009 and latest date was 2016
summary(df[['first_inspection_year']])

# Create a new column with number of years since the first inspection was reported
df$years_since_first <- 2020 - df$first_inspection_year
# summary(df[['years_since_first']])

# There is only 1 home with fewer than 5 years of inspections, Royal Rose Place
table(df['years_since_first'])
subset(df, years_since_first == 4)

```


```{r, include=FALSE}
# # Replace NAN values with 0 for inspections data
# dput(names(df))
# 
# ls = c("total_inspections", "X5y_inspections", "X2y_inspections", 
#        "total_complaints", "X5y_complaints", "X2y_complaints", "total_critical", 
#        "X5y_critical", "X2y_critical", "total_withOrders", "X5y_withOrders", 
#        "X2y_withOrders")
# 
# df[ls][is.na(df[ls])] <- 0

# Add derived variables
# Add a column with outbreak status
# df$outbreak <- with(df, ifelse(is.na(Status), 'no', 'yes'))

# Number of complaints/beds
df$total_complaints_norm <- df$total_complaints/df$number_beds/df$years_since_first
df$X5y_complaints_norm <- df$X5y_complaints/df$number_beds/5
df[444, "X5y_complaints_norm"] <- df[444, "X5y_complaints_norm"]*5/4
df$X2y_complaints_norm <- df$X2y_complaints/df$number_beds/2

# Number of inspections/beds
df$total_inspections_norm <- df$total_inspections/df$number_beds/df$years_since_first
df$X5y_inspections_norm <- df$X5y_inspections/df$number_beds/5
df[444, "X5y_inspections_norm"] <- df[444, "X5y_inspections_norm"]*5/4
df$X2y_inspections_norm <- df$X2y_inspections/df$number_beds/2

# Number of noncomplaints/beds
df$total_noncomplaints_norm <- (df$total_inspections - df$total_complaints)/df$number_beds/df$years_since_first
df$X5y_noncomplaints_norm <- (df$X5y_inspections - df$X5y_complaints)/df$number_beds/5
df[444, "X5y_noncomplaints_norm"] <- df[444, "X5y_noncomplaints_norm"]*5/4
df$X2y_noncomplaints_norm <- (df$X2y_inspections - df$X2y_complaints)/df$number_beds/2

```

```{r, echo=FALSE}
# Change variable types
# Update data types for some columns
df[, 'outbreak'] <- as.factor(df[, 'outbreak'])

# Change data type of character
listofcol = list('name', 'cleaned_name', 'address', 'city', 'postal_code', 'CSDname')
for (each in listofcol){
  df[, each] <- as.character(df[, each])
}

skim(df)
```


```{r, }
# Generate the data for analysis
# Create lists of variables used to filter data for analysis
keep = c("outbreak", "home_type", "number_beds")
profile = c("short_stay", "residents_council", "family_council", "accreditation")
location = c('address', 'LHIN', 'city', 'postal_code', 'CSDname', 'CSDuid', 'latitude', 'longitude')

all_inspections = c("total_inspections_norm"
  , "X5y_inspections_norm"
  , "X2y_inspections_norm"
  )
complaints = c("total_complaints_norm"
  , "X5y_complaints_norm"
  , "X2y_complaints_norm"
  )
noncomplaints = c("total_noncomplaints_norm"
  , "X5y_noncomplaints_norm"
  , "X2y_noncomplaints_norm"
  )

all_inspections_recent = c("X5y_inspections_norm", "X2y_inspections_norm")
complaints_recent = c("X5y_complaints_norm", "X2y_complaints_norm")
noncomplaints_recent = c("X5y_noncomplaints_norm", "X2y_noncomplaints_norm")

# covid = c("confirmed_resident_cases", "resident_deaths", "confirmed_staff_cases")

```


```{r }
# data <- subset(df, select = c(keep, profile, all_inspections, complaints))
# data <- subset(df, select = c(keep, profile, noncomplaints, complaints))
# data <- subset(df, select = c(keep, profile, noncomplaints_recent, complaints_recent))
# data <- subset(df, select = c(keep, profile, all_inspections_recent, complaints_recent))

data_lr <- subset(df, select = c(keep, profile, 'total_noncomplaints_norm', 'total_complaints_norm'))
data_lr_recent <- subset(df, select = c(keep, profile, 'X5y_noncomplaints_norm', 'X5y_complaints_norm'))

skim(data)
# dput(names(df))
```

LASSO
```{r }
# https://stats.stackexchange.com/questions/72251/an-example-lasso-regression-using-glmnet-for-binary-outcome
library(glmnet)

# model.matrix() automatically transforms any qualitative variables into dummy variables
# Trim the first column leaving only predictors
x = model.matrix(outbreak~., data = data)[,-1]
# y <- as.matrix(subset(data, select = c('outbreak')))
y <- data.matrix(data[,1])

# Note alpha=1 for lasso only and can blend with ridge penalty down to
# alpha=0 ridge only
glmmod <- glmnet(x, y=as.factor(y), alpha = 1, family = 'binomial')

# Plot variable coefficients vs. shrinkage parameter lambda
plot(glmmod, xvar = 'lambda', label = TRUE)

cv.glmmod <- cv.glmnet(x, y, alpha=1, family = 'binomial')


plot(cv.glmmod)
cv.glmmod$lambda.min

coef(cv.glmmod, s = "lambda.min")

summary(glmmod)

```

```{r }
library(MASS)
null <- glm(outbreak ~ 1, family = "binomial", data=data) # 1 here means the intercept 
# full <- glm(outbreak ~ home_type + number_beds + short_stay +
#     residents_council + family_council + accreditation + 
#     total_inspections_norm + X5y_inspections_norm + X2y_inspections_norm + 
#     total_noncomplaints_norm + X5y_noncomplaints_norm + X2y_noncomplaints_norm + 
#     total_complaints_norm + X5y_complaints_norm + X2y_complaints_norm, 
#   family = 'binomial', data = data)
# 
# full <- glm(outbreak ~ home_type + number_beds + short_stay +
#     residents_council + family_council + accreditation + 
#     total_noncomplaints_norm + X5y_noncomplaints_norm + X2y_noncomplaints_norm + 
#     total_complaints_norm + X5y_complaints_norm + X2y_complaints_norm, 
#   family = 'binomial', data = data)

full <- glm(outbreak ~ home_type + number_beds + short_stay +
    residents_council + family_council + accreditation + 
    # total_inspections_norm + 
    # X5y_inspections_norm + X2y_inspections_norm + 
    total_complaints_norm +
    # X5y_complaints_norm + 
    # X2y_complaints_norm +
    total_noncomplaints_norm
    # + X5y_noncomplaints_norm
    # + X2y_noncomplaints_norm
    ,
  family = 'binomial', data = data)

stepAIC(full, scope=list(lower=null, upper=full), data=data, direction='backward')
# stepAIC(null, scope=list(lower=null, upper=full), data=data, direction='forward')
# stepAIC(full, k = log(nrow(data)))
```

## Fit logistic regression
```{r }
# fit logistic regression using transformed data
fit = glm(outbreak~., family='binomial', data=data_lr)
fit_recent = glm(outbreak~., family='binomial', data=data_lr_recent)
summary(fit)
summary(fit_recent)
```

### Backwards selection
```{r, include=FALSE}
# Manual
fit <- update(fit, .~. -total_inspections_norm)
summary(fit)
fit <- update(fit, .~. -X2y_inspections_norm)
summary(fit)
fit <- update(fit, .~. -X5y_inspections_norm)
summary(fit)
fit <- update(fit, .~. -X2y_complaints_norm)
summary(fit)
fit <- update(fit, .~. -X2y_noncomplaints_norm)
summary(fit)
fit <- update(fit, .~. -X5y_complaints_norm)
summary(fit)
fit <- update(fit, .~. -total_noncomplaints_norm)
summary(fit)
fit <- update(fit, .~. -X5y_noncomplaints_norm)
summary(fit)
fit <- update(fit, .~. -family_council)
summary(fit)
fit <- update(fit, .~. -accreditation)
summary(fit)
fit <- update(fit, .~. -residents_council)
summary(fit)
fit <- update(fit, .~. -short_stay)
summary(fit)
fit <- update(fit, .~. -X2y_noncomplaints_norm)
summary(fit)
fit <- update(fit, .~. -total_complaints_norm)
summary(fit)

```


## Transforming the Predictors
```{r, }
## Assessing skewness
# Check for R skewness in numeric predictors
library(e1071)

listofcols = c('number_beds', complaints, noncomplaints, all_inspections)

for (each in listofcols){
  print(each)
  print(skewness(data[[each]]))
  qqnorm(data[[each]], main = each)
  qqline(data[[each]], col = 'red')
}

for (each in listofcols){
  print(each)
  print(summary(df[[each]]))
}

# Create a list of numeric variables with 0 values
list0s <- c(complaints, "X2y_noncomplaints_norm")

library(rcompanion)
listofcols <- setdiff(listofcols, list0s)

# Visualize the effect of square root and log transformations on the data without 0s
for (each in listofcols) {  
  plotNormalHistogram(x = data[[each]], main = each)
  plotNormalHistogram(x = sqrt(data[[each]]), main = c(each, 'sqrt trans'))
  plotNormalHistogram(x = log(data[[each]]), main = c(each, 'log trans'))
}

# Visualize the effect of a square root transformation on the variables with 0s
for (each in list0s) {  
  plotNormalHistogram(x = data[[each]], main = each)
  plotNormalHistogram(x = sqrt(data[[each]]), main = c(each, 'sqrt trans'))
}

# Log transform in place

data[c("total_noncomplaints_norm", "X5y_noncomplaints_norm", all_inspections)] <- log(data[c("total_noncomplaints_norm", "X5y_noncomplaints_norm", all_inspections)])

# Square root transform in place
data[c('number_beds', list0s)] <- sqrt(data[c('number_beds', list0s)])

skim(data)
```

```{r }
# Calculate McFadden's pseudo R2
ll.null <- fit$null.deviance/-2
ll.proposed <- fit$deviance/-2
print((ll.null - ll.proposed)/ll.null)
1 - pchisq(2*(ll.proposed - ll.null), df = (length(fit$coefficients)-1)) #pvalue

```

## Visualize the model
```{r, echo=FALSE}
# Create a new dataframe showing probability of outbreak and outbreak status
predicted.data <- data.frame(probability.of.outbreak=fit$fitted.values, outbreak=data$outbreak)

# Sort the above df
predicted.data <- predicted.data[order(predicted.data$probability.of.outbreak, decreasing=FALSE),]

# Add new col to df with rank
predicted.data$rank <- 1:nrow(predicted.data)

library(ggplot2)
# library(cowplot)

ggplot(data = predicted.data, aes(x=rank, y=probability.of.outbreak)) +
  geom_point(aes(color=outbreak), alpha = 0.5, shape = 4, stroke = 1) +
  xlab("Index") + ylab("Predicted probability of an outbreak") +
  ggtitle("Outbreak Status Ordered By Predicted Probability of an Outbreak") + 
  scale_color_manual(values = c('blue', 'red'))

```



```{r }

```

```{r }

```


```{r }

```


```{r }

```


```{r }

```
