---
title: "Nursing Home COVID Mortality Zero Inflated Model"
output:
  html_document: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Require R Packages, include=FALSE}
library(sp)
library(tidyverse)
library(rgdal)
library(maps)
library(tidyverse)
# install.packages('INLA', repos=c(getOption('repos'),INLA='https://inla.r-inla-download.org/R/testing'),dep=TRUE)
library(INLA)
library(geostatsp)
library(mapmisc)
library(leaflet)
```

```{r Get Data: Pollution Stations and Boundary shp, include=FALSE}
nursing_home <- read.csv2('/Users/kt/Documents/covid-research/wrangle_covid/data/BC/bc_ltc_selected_sep18.csv', sep=',')
nursing_home
#Canada = raster::getData('GADM', country='CA', level=1)
nursing_home$latitude <- as.numeric(as.character(nursing_home$latitude))
nursing_home$longitude <- as.numeric(as.character(nursing_home$longitude))
# Fix the Bad Coordinate

# Create anyCases column
i = 1
for (i in 1:294) {
  if (nursing_home$Total.Confirmed.Cases[i] == 0.0) {
    nursing_home$anyCases[i] = 0
  } else {
    nursing_home$anyCases[i] = 1
  }
}
```

```{r prepareData}

# prepare data
nursing_home$logBed=log(nursing_home$BEDS_TOTAL)
nursing_home$Total.Deaths<-as.character(nursing_home$Total.Deaths)
# i = 1
for (i in 1:nrow(nursing_home)){
  if (nursing_home$Total.Deaths[i] == '<5') {
    nursing_home$Total.Deaths[i] = '1'
  }}
nursing_home$Total.Deaths <- as.numeric(nursing_home$Total.Deaths)
coordinates(nursing_home) <- c('longitude', 'latitude')

crs(nursing_home) <- CRS("+init=epsg:4326")

```

```{r leafletLegend}

addLegendCustom <- function(map, colors, labels, sizes, font.sizes, opacity = 0.8, group){
  colorAdditions <- paste0(colors, "; width:", sizes, "px; height:", sizes, "px")
  labelAdditions <- paste0("<div style='display: inline-block;height: ", font.sizes, "px;margin-top: 4px;line-height: ", font.sizes, "px;'>", labels, "</div>")
  
  return(addLegend(map, colors = colorAdditions, labels = labelAdditions, group = group, opacity = opacity))
}


```


```{r all nursing homes}
library(shiny)

## All Nursing Homes in BC Leaflet Map
par(mar=c(1, 1, 1, 1))
colBreaks <- c(0,0.01,10,25,40,70)

nursing_home$rate <- with(nursing_home@data, Total.Deaths/BEDS_TOTAL)
nursing_home <- nursing_home[order(nursing_home$Total.Deaths, na.last=FALSE),]
ptCol <- colourScale(nursing_home$Total.Deaths, breaks=colBreaks, style='fixed',
                                         col="YlOrRd")
ptCol$plot <- ifelse(is.na(ptCol$plot), "#000000", ptCol$plot)

legendLabs <- sapply(seq(ptCol$breaks)[-1], function(i) { 
  paste0(ptCol$breaks[i-1],' - ',ptCol$breaks[i])
})

leaflet(nursing_home) %>%
  addTiles() %>%
  addCircleMarkers(#lng = ~longitude, lat = ~latitude, 
    label = ~ as.character(FACILITY_NAME), 
             fillColor = ptCol$plot, fillOpacity = 0.8, radius = 4, stroke = FALSE) %>% 
      addLegendCustom(colors = ptCol$col, labels = legendLabs, sizes = 6, font.sizes = 2, group='Total.Deaths')

```

```{r}
ptCol2 <- colorFactor("YlOrRd", levels(nursing_home$OWNERSHIP), na.color = "#000000")
legendLabs2 <- levels(nursing_home$OWNERSHIP)

mapcolours <- unique(ptCol2(nursing_home$OWNERSHIP))

leaflet(nursing_home) %>%
  addTiles() %>%
  addCircleMarkers(#lng = ~longitude, lat = ~latitude, 
    label = ~ OWNERSHIP, 
             fillColor = ptCol2(nursing_home$OWNERSHIP), fillOpacity = 0.8, radius = 4, stroke = FALSE) %>%
  addLegendCustom(colors = mapcolours, labels = legendLabs2, sizes = 6, font.sizes = 2, group='Ownership Type')

```

```{r setProj}

projTrans <- CRS("+proj=omerc +lat_0=43.869 +lonc=-78.882 +alpha=-80 +k_0=1 +x_0=0 +y_0=0 +gamma=-48 +ellps=WGS84 +units=m +datum=WGS84 +towgs84=0,0,0")

mapTrans <- CRS("+init=epsg:3162")

```

## Model 6: Zero-Inflated Poisson Model W/ Individual Effect - Southern Ontario Nursing Homes; buffer 100km

```{r model_6_southOn}

# # subset data
# nursingHome_southOn <- nursing_home[substr(trimws(nursing_home$postal_code),1,1)!='P',]
# crs(nursingHome_southOn) <- CRS("+init=epsg:4326")
# nursingHome_southOn_proj <- spTransform(nursingHome_southOn, projTrans)
# 
# # model
# Res6 = geostatsp::glgm(resident_deaths ~ offset(logBed) #why is this offsetted?
#                                             + total_complaints 
#                                             + home_type 
#                                             + total_inspections 
#                                             + f(cleaned_name), 
#                          data=nursingHome_southOn_proj, 
#                          grid=200, 
#                          buffer=100*1000,
#                          family='zeroinflatedcenpoisson0',
#                          control.family = list(cenpoisson.I = c(1,4)))
# # summary
# Res6$parameters$summary
# Res6$inla$summary.hyperpar
```



```{r select_res}

# res <- Res6

```

```{r map_setup}

# # Boundaries
# canada = raster::getData("GADM", country="CAN", level=2)
# canadaTrans <- spTransform(canada, projTrans)
# ontario <- canada[canada$NAME_1 == 'Ontario',]
# ontarioTrans <- spTransform(ontario, projTrans)
# 
# # Census division
# cdShp <- rgdal::readOGR(layer='lcd_000a16a_e', dsn=file.path('~/maggie','lcd_000a16a_e.shp'))
# onShp <- cdShp[cdShp$PRUID=='35',]
# onShpTrans <- sp::spTransform(onShp, CRSobj=mapTrans)
# 
# # Prediction
# pred <- res$raster$predict.exp
# if (is.null(crs(pred))) {
#   crs(pred) <- CRS("+init=epsg:4326")
#   predTrans <- projectRaster(pred, crs=mapTrans)
# } else {
#   predTrans <- pred
#   predTrans <- projectRaster(pred, crs=mapTrans)
# }
# 
# predTransMask <- mask(predTrans, onShpTrans) # Masking prediction raster
# 
# # Random effect
# rand <- res$raster$random.exp
# if (is.null(crs(rand))) {
#   crs(rand) <- CRS("+init=epsg:4326")
#   randTrans <- projectRaster(rand, crs=mapTrans)
# } else {
#   randTrans <- rand
#   randTrans <- projectRaster(rand, crs=mapTrans)
# }
# 
# randTransMask <- mask(randTrans, onShpTrans) # Masking random effect raster
# 
# #spTransform(mydata, projTrans)
# 
# # Some cities
# someCities = mapmisc::geocode(c("Toronto","Windsor","Ottawa","Whitby"))
# someCitiesTrans <- spTransform(someCities, mapTrans)

```

```{r shadowText}

# Function for shadow text
# http://article.gmane.org/gmane.comp.lang.r.general/147787

shadowtext <- function(x, y=NULL, labels, col='black', bg='white',
                       theta= seq(pi/4, 2*pi, length.out=8), r=0.1, ... ) {
  
  xy <- xy.coords(x,y)
  xo <- r*strwidth('A')
  yo <- r*strheight('A')
  
  for (i in theta) {
    text( xy$x + cos(i)*xo, xy$y + sin(i)*yo, labels, col=bg, ... )
  }
  text(xy$x, xy$y, labels, col=col, ... )
}

```

```{r offsetLabel}

offsetLabel <- function(spatial.df, map.extent, pos='bottomright', offset=2) {
  offsetX = (diff(map.extent[1:2])/100)*offset
  offsetY = (diff(map.extent[3:4])/100)*offset
  
  if (pos=='bottomright') {
    coords <- cbind(spatial.df@coords[,1]+offsetX, spatial.df@coords[,2]-offsetY)
  } else if (pos=='bottomleft') {
    coords <- cbind(spatial.df@coords[,1]-offsetX, spatial.df@coords[,2]-offsetY)
  } else if (pos=='topright') {
    coords <- cbind(spatial.df@coords[,1]+offsetX, spatial.df@coords[,2]+offsetY)
  } else if (pos=='topleft') {
    coords <- cbind(spatial.df@coords[,1]-offsetX, spatial.df@coords[,2]+offsetY)
  } 
  
  spatial.df@coords <- coords
  return(spatial.df)
} 

```

```{r zero inflated model map ON, eval=FALSE, include=FALSE}

# predicted map
# mapmisc::map.new(nursing_home)
# plot(res$raster$predict.exp, add=TRUE, col=grDevices::heat.colors(6, rev=TRUE))
# #Themap3 = mapmisc::tonerToTrans(mapmisc::openmap(nursing_home, path='stamen-toner'))
# #plot(Themap3, add=TRUE)
# 
# #spTransform(mydata, projTrans)
# 
# # Boundaries
# canada = raster::getData("GADM", country="CAN", level=2)
# plot(canada, add=TRUE)
# 
# points(someCities)
# text(someCities@coords, labels = someCities$name)

```

### Map results from Zero Inflated Censored Poisson model

```{r map_hana, cache=TRUE, fig.width=8, fig.height=6}

# mapExtent <- extent(onShpTrans)
# someCitiesTrans2 <- offsetLabel(someCitiesTrans, mapExtent, pos='bottomright', offset=1)
# 
# # predicted map
# quantile(predTransMask, prob=c(0:6/6))
# pCols = mapmisc::colourScale(
#     #breaks=c(0.1984, 0.19845, 0.1985, 0.19851, 0.19852, 0.19853, 0.19854, 0.19855, 0.1986),
#   #breaks=c(0.1988,0.19882,0.19884,0.19886,0.19888,0.198882, 0.198884, 0.198886, 0.198888,0.1990),
#   #breaks=c(0.15904,0.15905,0.15906,0.15907,0.15908,0.15909,0.15910),
#   breaks=c(0.16316,0.16322,0.16323,0.16324,0.16325,0.16326,0.16328),
#     col='Spectral', rev=TRUE, style='fixed')
# 
# mapmisc::map.new(predTransMask)
# plot(predTransMask, breaks = pmax(-100,pCols$breaks), col=pCols$col, legend=FALSE)
# plot(onShpTrans, border=grey(0.5), add=TRUE)
# #Themap3 = mapmisc::tonerToTrans(mapmisc::openmap(nursing_home, path='stamen-toner'))
# #plot(Themap3, add=TRUE)
# points(someCitiesTrans, pch=16, cex=0.9)
# shadowtext(someCitiesTrans2@coords, labels = someCitiesTrans2$name, cex=0.8, font=1, adj=0)
# lgdBreaks <- mapmisc::legendBreaks("bottomright", pCols, cex=0.8, box.lwd = 0,box.col = "white", inset=c(0.25,0.08))
# lgdBreaks
# lgdBreaksRect <- lgdBreaks[['rect']]
# text(x=lgdBreaksRect$left+3000, y=lgdBreaksRect$top-8000, labels='Predicted death rates', adj=0, font=2, cex=0.8)
# 
# # random effect map
# quantile(randTransMask, prob=c(0:7/7))
# pCols = mapmisc::colourScale(
#     #breaks=c(1.0026,1.0028, 1.0029, 1.003,1.0031, 1.0032, 1.0033, 1.0035),
#     #breaks=c(1.0136,1.0137,1.0138,1.0139,1.014,1.0141,1.0142,1.0144),
#     #breaks=c(1.0029,1.0030,1.00302,1.00304,1.00306,1.00308,1.0031,1.0033),
#     breaks=c(1.00816,1.0094,1.0095,1.0096,1.0097,1.0098,1.0103),
#     col='Spectral', rev=TRUE, style='fixed')
# 
# mapmisc::map.new(randTransMask)
# plot(randTransMask, breaks = pmax(-100,pCols$breaks), col=pCols$col, legend=FALSE)
# plot(onShpTrans, border=grey(0.5), add=TRUE)
# #Themap3 = mapmisc::tonerToTrans(mapmisc::openmap(nursing_home, path='stamen-toner'))
# #plot(Themap3, add=TRUE)
# points(someCitiesTrans, pch=16, cex=0.7)
# shadowtext(someCitiesTrans2@coords, labels = someCitiesTrans2$name, cex=0.8, font=1, adj=0)
# lgdBreaks <- mapmisc::legendBreaks("bottomright", pCols, cex=0.8, box.lwd = 0,box.col = "white", inset=c(0.25,0.08))
# lgdBreaks
# lgdBreaksRect <- lgdBreaks[['rect']]
# text(x=lgdBreaksRect$left+3000, y=lgdBreaksRect$top-8000, labels='Random effects', adj=0, font=2, cex=0.8)
# # scalebar(1000*50, xy=c(lgdBreaksRect$left-200000, lgdBreaksRect$top-lgdBreaksRect$h), 
# #          type='line', label=c('0',NA,'50km'))

```

## Model 7: Binomial Model W/ Individual Effect - Southern Ontario Nursing Homes; buffer 100km


```{r Binomial Model}
# Res7 = geostatsp::glgm(anyCases ~ offset(logBed) 
#                                             + total_complaints 
#                                             + home_type 
#                                             + total_inspections 
#                                             + f(cleaned_name), 
#                          data=nursingHome_southOn_proj, 
#                          grid=200,
#                          buffer=100*1000,
#                          family='binomial')
# 
# Res7$parameters$summary
```

```{r select_res2}
# 
# res <- Res7

```

```{r map_setup2}
# 
# # Prediction
# pred <- res$raster$predict.exp
# if (is.null(crs(pred))) {
#   crs(pred) <- CRS("+init=epsg:4326")
#   predTrans <- projectRaster(pred, crs=mapTrans)
# } else {
#   predTrans <- pred
#   predTrans <- projectRaster(pred, crs=mapTrans)
# }
# 
# predTransMask <- mask(predTrans, onShpTrans) # Masking prediction raster
# 
# # Random effect
# rand <- res$raster$random.exp
# if (is.null(crs(rand))) {
#   crs(rand) <- CRS("+init=epsg:4326")
#   randTrans <- projectRaster(rand, crs=mapTrans)
# } else {
#   randTrans <- rand
#   randTrans <- projectRaster(rand, crs=mapTrans)
# }
# 
# randTransMask <- mask(randTrans, onShpTrans) # Masking random effect raster
# 
# #spTransform(mydata, projTrans)
# 
# # Some cities
# #someCities = mapmisc::geocode(c("Toronto","Windsor","Ottawa","Whitby"))
# #someCitiesTrans <- spTransform(someCities, mapTrans)

```


### Map results from Binomial model


```{r map2, cache=TRUE, fig.width=8, fig.height=6}
# 
# mapExtent <- extent(onShpTrans)
# someCitiesTrans2 <- offsetLabel(someCitiesTrans, mapExtent, pos='bottomright', offset=1)
# 
# # predicted map
# quantile(predTransMask, prob=c(0:6/6))
# pCols = mapmisc::colourScale(
#     #breaks=c(0.1984, 0.19845, 0.1985, 0.19851, 0.19852, 0.19853, 0.19854, 0.19855, 0.1986),
#   #breaks=c(0.1988,0.19882,0.19884,0.19886,0.19888,0.198882, 0.198884, 0.198886, 0.198888,0.1990),
#   #breaks=c(0.15904,0.15905,0.15906,0.15907,0.15908,0.15909,0.15910),
#   breaks=c(0.00027,0.00052,0.00059,0.00063,0.00066,0.00071,0.00324),
#     col='Spectral', rev=TRUE, style='fixed')
# 
# mapmisc::map.new(predTransMask)
# plot(predTransMask, breaks = pmax(-100,pCols$breaks), col=pCols$col, legend=FALSE)
# plot(onShpTrans, border=grey(0.5), add=TRUE)
# #Themap3 = mapmisc::tonerToTrans(mapmisc::openmap(nursing_home, path='stamen-toner'))
# #plot(Themap3, add=TRUE)
# points(someCitiesTrans, pch=16, cex=0.9)
# shadowtext(someCitiesTrans2@coords, labels = someCitiesTrans2$name, cex=0.8, font=1, adj=0)
# lgdBreaks <- mapmisc::legendBreaks("bottomright", pCols, cex=0.8, box.lwd = 0,box.col = "white", inset=c(0.25,0.08))
# lgdBreaks
# lgdBreaksRect <- lgdBreaks[['rect']]
# text(x=lgdBreaksRect$left+3000, y=lgdBreaksRect$top-8000, labels='Predicted death rates', adj=0, font=2, cex=0.8)
# 
# # random effect map
# quantile(randTransMask, prob=c(0:7/7))
# pCols = mapmisc::colourScale(
#     #breaks=c(1.0026,1.0028, 1.0029, 1.003,1.0031, 1.0032, 1.0033, 1.0035),
#     #breaks=c(1.0136,1.0137,1.0138,1.0139,1.014,1.0141,1.0142,1.0144),
#     #breaks=c(1.0029,1.0030,1.00302,1.00304,1.00306,1.00308,1.0031,1.0033),
#     breaks=c(0.649,1.321,1.499,1.610,1.664,1.836,9.116),
#     col='Spectral', rev=TRUE, style='fixed')
# 
# mapmisc::map.new(randTransMask)
# plot(randTransMask, breaks = pmax(-100,pCols$breaks), col=pCols$col, legend=FALSE)
# plot(onShpTrans, border=grey(0.5), add=TRUE)
# #Themap3 = mapmisc::tonerToTrans(mapmisc::openmap(nursing_home, path='stamen-toner'))
# #plot(Themap3, add=TRUE)
# points(someCitiesTrans, pch=16, cex=0.7)
# shadowtext(someCitiesTrans2@coords, labels = someCitiesTrans2$name, cex=0.8, font=1, adj=0)
# lgdBreaks <- mapmisc::legendBreaks("bottomright", pCols, cex=0.8, box.lwd = 0,box.col = "white", inset=c(0.25,0.08))
# lgdBreaks
# lgdBreaksRect <- lgdBreaks[['rect']]
# text(x=lgdBreaksRect$left+3000, y=lgdBreaksRect$top-8000, labels='Random effects', adj=0, font=2, cex=0.8)
# # scalebar(1000*50, xy=c(lgdBreaksRect$left-200000, lgdBreaksRect$top-lgdBreaksRect$h), 
# #          type='line', label=c('0',NA,'50km'))

```
