---
title: "BC LTC Parameters"
author: "KT Hobbs"
date: "06/08/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## General Home Information

Parameter | Type | Description
----------|------|------------
`FACILITY_NAME` | string | Name of long-term care facility.
`Number of dead` | float64 | As reported by [Nora Loreto](https://docs.google.com/spreadsheets/d/1M_RzojK0vwF9nAozI7aoyLpPU8EA1JEqO6rq0g1iebU/edit#gid=0).
`HCC_CODE` | string | Unique identifier of facility.
`HLTH_AUTH` | string | Name of health authority that home resides in.
`STREET_ADDRESS` | string | Street address.
`CITY` | string | City.
`POSTAL` | string | Postal code.
`PHONE` | string | Phone.
`OPEN_DATE` | string | Year LTC opened.
`point` | | Location coordinates.
`latitude` |  | Latitude of home.
`longitude` | | Longitude of home.



## Detailed Home Information

Parameter | Type | Description
----------|------|------------
`COUNCIL` | string | List of councils operating in home. A family and/or resident  council is also self-led, self-determining and democratic. Councils exist to engage the resident community in collaborative activities which will advance the quality of life for residents. $^{(1)}$
`residents_council` | binary string | "yes" or "no".
`family_council` | binary string | "yes" or "no".
`ACCRED_STATUS` | string | Accreditation is a voluntary process that LTC homes may use to assess their services and help them improve the quality, safety and efficiency of their performance for the benefit of their residents and the health system $^{(2)}$.
`accreditation` | binary string | "yes" or "no".
`BEDS_PRIVATE` | int64 | Number of private beds in facility.
`BEDS_PUBLIC` | int64 | Number of public beds in facility.
`BEDS_TOTAL` | int64 | Total number of beds in facility.
`ROOMS_PRIVATE` | int64 | Number of private rooms.
`ROOMS_SEMI` | int64 | Number of semi-private rooms (2 beds).
`ROOMS_MULTI` | int64 | Number of mult-persons rooms (3+ beds).
`home_type` | string | Home operation - either for profit, non-profit, or health authority.
`ownership_type` | string | Funding - either public or private (for profit, non-profit homes).
`years_operation` | float64 | Number of years a home has operated for.


## Quality Metrics$^3$

Parameter | Type | Description
----------|------|------------
`COMPLAINTS` | int64 | Number of licensing complaints.
`COMPLAINTS_SUB` | int64 | Number of substantiated licensing complaints.
`INCIDENT_OUTBREAK` | int64 | Total disease or outbreak occurences.
`INCIDENT_ABUSE` | int64 | Total documented cases of abuse or neglect.
`INCIDENT_FALL` | int64 | Total documented cases of falls with injury / adverse events.
`INCIDENT_POISON` | int64 | Total documented cases of food or other poisonings.
`INCIDENT_MEDICATION` | int64 | Total documented cases of medication error with adverse event.
`INCIDENT_WANDERING` | int64 | Total documented cases of missing or wandering person.
`INCIDENT_INJURY` | int64 | Total documented cases of other injury.
`INCIDENT_AGGRESSION` | int64 | Total documented cases of aggression between persons in care.
`INCIDENT_OUTBREAK_100` | int64 | Per 100 beds, disease or outbreak occurences.
`INCIDENT_ABUSE_100` | int64 | Per 100 beds, documented cases of abuse or neglect.
`INCIDENT_FALL_100` | int64 | Per 100 beds, documented cases of falls with injury / adverse events.
`INCIDENT_POISON_100` | int64 | Per 100 beds, documented cases of food or other poisonings.
`INCIDENT_MEDICATION_100` | int64 | Per 100 beds, documented cases of medication error with adverse event.
`INCIDENT_WANDERING_100` | int64 | Per 100 beds, documented cases of missing or wandering person.
`INCIDENT_INJURY_100` | int64 | Per 100 beds, documented cases of other injury.
`INCIDENT_AGGRESSION_100` | int64 | Per 100 beds, documented cases of aggression between persons in care.
`INSPECTIONS` | float64 | Number of inspections.
`INFRACTIONS` | float64 | Number of licensing infractions found.
`INFRACTIONS_LICENSING` | float64 | Licensing infractions - Licensing.
`INFRACTIONS_FACILITY` | float64 | Licensing infractions - physcial facility, equipment & furnishings.
`INFRACTIONS_STAFFING` | float64 | Licensing infractions - staffing.
`INFRACTIONS_POLICY` | float64 | Licensing infractions - policies & procedures.
`INFRACTIONS_CARE` |float64 | Licensing infractions - care & supervision.
`INFRACTIONS_DISEASE` | float64 | Licensing infractions - hygiene & communicable disease control.
`INFRACTIONS_FOOD` | float64 | Licensing infractions - nutrition & food services.
`INFRACTIONS_MEDICATION` | float64 | Licensing infractions - medication.
`INFRACTIONS_PROGRAM` | float64 | Licensing infractions - program.
`INFRACTIONS_REPORTING` | float64 | Licensing infractions - records & reporting.
`INFRACTIONS_RIGHTS` | float64 | Licensing infractions - resident bill of rights.
`INFRACTIONS_OTHER` | float64 | Licensing infractions - other.


## General Resident Profile

Parameter | Type | Description
----------|------|------------
`AGE` | int64 | Average age of population.
`FEMALE` | int64 | Percent female.
`AGE_85_PLUS` | int64 | Percent 85 years or older.
`AGE_UNDER_65` | int64 | Percent younger than 65 years.
`STAY_LENGTH` | int64 | Average length of stay
`DEPRESSION` | float64 | Percent of residents diagnosed with depression
`ADL_DEPENDENT` |float64  | Percent of residents dependent in activities of daily living
`CPS_SEVERE` | float64 | Percent of residents with severe cognitive impairment
`DEMENTIA` |  float64 | Percent of residents with dementia
`ABS_PHYS_ABUSIVE` | float64 | Percent of residents with physically abusive behaviour
`ISE` | float64  | Average index of social engagement
`ISE_LOW` | float64 | Percent of residents with low social engagement
`CMI` | float64 | Case mix index
`THERAPY_PT` | float64 | Percents of residents receiving physical therapy
`THERAPY_RT` | float64 | Percents of residents receiving recreation therapy
`THERAPY_OT` | float64 | Percents of residents receiving occupational therapy
`MEDS_DEPRESSION` | float64 | Percent of residents receiving depression medication
`MEDS_ANTIPSYCHOTICS` | float64 | Percent of residents taking antipsychotics without a diagnosis of psychosis
`RESTRAINTS` | float64 | Percent of residents with daily physical restraints


## COVID-19 Related Parameters

Parameter | Type | Description
----------|------|------------
`outbreak_status` | binary string | "yes" (outbreak has occured) or "no" (outbreak has not occured)
`Number of dead` | int64/string | Number of dead as reported by Nora Loreto$^{4}$. For homes with an outbreak (according to government websites $^{5}$) but not included in Nora's report, `"unreported"` was imputed.

---

$^1$ [https://www2.gov.bc.ca/gov/content/health/accessing-health-care/home-community-care/accountability/family-and-resident-councils](https://www2.gov.bc.ca/gov/content/health/accessing-health-care/home-community-care/accountability/family-and-resident-councils)

$^2$ [http://health.gov.on.ca/en/public/programs/ltc/glossary.aspx](http://health.gov.on.ca/en/public/programs/ltc/glossary.aspx)

$^3$ [Excel provided by Seniors Advocate Representative.]

$^4$ [https://docs.google.com/spreadsheets/d/1M_RzojK0vwF9nAozI7aoyLpPU8EA1JEqO6rq0g1iebU/edit#gid=0](https://docs.google.com/spreadsheets/d/1M_RzojK0vwF9nAozI7aoyLpPU8EA1JEqO6rq0g1iebU/edit#gid=0)

$^5$ [http://www.phsa.ca/current-outbreaks](http://www.phsa.ca/current-outbreaks) 


\pagebreak

[] Dealing with sparsity and NA's; mostly apparent in `INCIDENT_*` and `INFRACTIONS_*` predictors, omission removes many homes. Some homes have up to 27 NAs. Currently, set to 0. `glm` can't handle NAs.

[] Skewed predictors. Log and square-root transformations ineffective at mediating skewness.

[] assumptions - nonlinear relationship of predictors with `outbreak_status`


